### ISSUE TITLE
Erro na escrita

### ISSUE THREAD

**Issue by cinthiaab** [digitalinnovationone/roadmaps#1]
Estava fazendo o quiz, quando notei esse pequeno errinho na escrita da palavra "interface".

![image](https://user-images.githubusercontent.com/87292056/214504610-e671e9d1-7f7e-483a-ade7-3c3b19012b85.png)

**Comment by falvojr** [comment]
Muito obrigado pela contribuição @cinthiaab e @jeffersonsimaogoncalves 👊🤩
