### ISSUE TITLE
corrigir carrers-cloud

### ISSUE THREAD

**Issue by Kassyacosta** [digitalinnovationone/roadmaps#19]
"name":"Sugestões de Cursos DIO",
        "description":"Devido as grandes vantagens de computação em nuvem cada vez mais sistemas, pipelines e fluxo de dados vem sendo implementados em nuvem. Sendo assim, saber criar sistemas como banco de dados, VMs, monitoramento, aplicações, servidores web, **(armasenamento/armazenamento)** de dados e outros recursos é um ponto **(importantissímo/importantíssimo)**. Logicamente, vai depender da sua função dentro da empresa. Criação de aplicações que possam interagir com a infraestrutura criada faz parte da vida de diversos profissionais de TI.",

**Comment by falvojr** [comment]
Muito obrigado pela colaboração @Kassyacosta, corrigido no commit #[d29a8a7](https://github.com/digitalinnovationone/roadmaps/commit/d29a8a7dae842dd78c11ff409c51aa9a16c8b551)
