### ISSUE TITLE
Erro na escrita - carreira CRM - issue #1

### ISSUE THREAD

**Issue by melquiedes** [digitalinnovationone/roadmaps#21]
Veja o anexo. Na dica sobre escrever "fazer a diferença para profissionais" é uma sugestão e não uma correção de erro.
Amei a ideia do roadmap e fiquei surprendido porque entrei na DIO para estudar Front End e o teste indicou CRM, preciso rever minhas trilhas.
![issues #1](https://user-images.githubusercontent.com/109827787/214753890-b4deceff-9764-41ea-ac01-a59d23e1fa18.jpg)

**Comment by melquiedes** [comment]
Se quiserem enviar as imagens dos outros roadmaps que não sejam "CRM", fique á vontade, será uma prazer verificar a ortografia.

**Comment by falvojr** [comment]
Vlw demais pelo feedback @melquiedes, vamos tratar desta correção no PR #23. Já te dei um feedback lá, tamo junto 👊😉

**Comment by melquiedes** [comment]
Opa!!! Tamo junto.
Vou acompanhar esse projeto com todo carinho, amei a ideia de ser "Open
Source"
A sensação foi muito boa quando depois de estudado um pouco mais de 100
horas na DIO e conseguir acessar o código no Git Hub e conseguir encontrar
o arquivo .json e fazer as correções. Me senti dev de verdade.
Isso anima muito.
Ainda mais tendo a oportunidades de constar como colaborador no projeto.
Muito top.
Outra coisa: algumas aulas sobre o git estudei nos teus vídeos na DIO.
Obrigado!!!!


Em qui, 26 de jan de 2023 12:49, Venilton FalvoJr ***@***.***>
escreveu:

**Comment by falvojr** [comment]
Sensacional @melquiedes, vlw demais pela colaboração amigo! Fiz os ajustes que comentei no PR #23 e já mandei pra `main`.

**Comment by melquiedes** [comment]
Valeu!  Eu vi o pedido agora. Muito obrigado!!!! Amigo!! sucesso!

Em seg., 30 de jan. de 2023 às 11:50, Venilton FalvoJr <
***@***.***> escreveu:
