### ISSUE TITLE
Padronização nos Botões de Compartilhar Via LinkedIn

### ISSUE THREAD

**Issue by falvojr** [digitalinnovationone/roadmaps#26]
@elidianaandrade vlw demais pela contribuição no PR #25, curti muito o header e o ajuste na paleta de cores. 

Sobre o botão de compartilhar no LinkedIn seria bem legal padronizarmos desta forma nas páginas específicas de cada Roadmap, ficou bem melhor  🤩 Nas páginas usamos um script do LinkedIn que inclui o botão, mas além de ser feio o código HTML ficou meio "sujo" com isso. Acrdeito que possamos padronizar esse botão no canto superior de todos os Roadmaps, deixando a UX igual em todo o projeto. O que acha?

**Comment by elidianaandrade** [comment]
Obrigada! Tudo bem! Estou fazendo as alterações dos botões e vou alterar esse texto também.
Obs.: Alterei o título da página Data Engineering, que estava como Analytics.

**Comment by falvojr** [comment]
Perfeito @elidianaandrade, muito obrigado! O PR #28 acabou de ser mergeado, fiz um comentário lá (uma dúvida na verdade) sobre usarmos um arquivo SVG pra padronizarmos o logo da DIO 😊
