### ISSUE TITLE
Adicionar UI e UX na Trilha de Front-End

### ISSUE THREAD

**Issue by IkkyLuiz** [digitalinnovationone/roadmaps#27]
Olá, equipe da Dio, acredito que o tema UI e UX deveriam ser adicionado a trilha de Front-End, principalmente pela importância de se criar um design responsivo e de fácil utilização para o usuário. Por isso acredito ser importante que conteúdos de UI e UX estejam presentes.

**Comment by falvojr** [comment]
Excelente ideia @IkkyLuiz, vlw demais pelo feedback! Faz todo sentido 😁
Incluí nossa Formação de UX no commit [4d657c2](https://github.com/digitalinnovationone/roadmaps/commit/4d657c251e816f9f8acf386a0a0808bd3033dde2)

**Comment by IkkyLuiz** [comment]
Fico feliz em ajudar @falvojr! Vamos juntos Make the change!
