### ISSUE TITLE
Revisão de Branding Com Recomendações de Melhoria nos Padrões Visuais

### ISSUE THREAD

**Issue by falvojr** [digitalinnovationone/roadmaps#43]
O time de Branding da DIO fez uma revisão técnica em nosso Roadmap de Carreiras 🤩
Para pacilitar a nossa vida, eles criaram um Figma, onde podemos visualizar as revisões e obter os assets necessários para as melhorias em questão: https://www.figma.com/file/TQ3lrK23T1NHrpt161aVIM/Revis%C3%A3o-github.io-roadmaps.?node-id=0%3A1

**Comment by falvojr** [comment]
@elidianaandrade tendo em vista sua colaboração fantástica na definição da identidade visual deste projeto, poderia deixar essa melhoria no seu backlog? 🙂

**Comment by elidianaandrade** [comment]
Massa! Posso sim!

**Comment by falvojr** [comment]
Muito obrigado @elidianaandrade, já aprovei o seu PR https://github.com/digitalinnovationone/roadmaps/pull/45 com os ajustes 🤩
