### ISSUE TITLE
Revisão dos Links das Formações

### ISSUE THREAD

**Issue by elidianaandrade** [digitalinnovationone/roadmaps#44]
Os links para as formações dentro das páginas dos Roadmaps precisam ser revisados, estão ficando como "https://web.dio.mehttps//web.dio.me/track/formacao", pois "https://dio.me/sign-in" está redirecionando para "https://web.dio.me/" agora.

**Comment by falvojr** [comment]
Fala @felipeAguiarCode, blz amigo? Estou colocando essa Issue pra ti porque comentamos sobre ela na semana passada e vc disse que poderia fazê-la 😊
Caso precise de algo me da um toque, por favor 😘

**Comment by felipeAguiarCode** [comment]
Links corrigidos e atualizados, muito obrigado pelo suporte @elidianaandrade  :)
